# Generated by Django 5.0.6 on 2024-08-31 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='book',
        ),
    ]
