# Generated by Django 5.0.6 on 2024-09-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrowers',
            new_name='borrower',
        ),
    ]
