# Generated by Django 5.0.6 on 2024-09-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type_borrowhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
